# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ming Sung
tagline:          The Software Developer
description:      Base theme for Jekyll themes by @mdo.
url:              http://getpoole.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

author:
  name:           Ming Sung
  url:            http://mingyuansung.github.com

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
